name: main
on:
  push:
    branches:
      - main
jobs:
  renovate:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Validate config
        run: jq type /default.json
