name: Renovate
on:
  push:
    branches:
      - main
jobs:
  validate:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Validate
        run: npx --yes --package renovate -- renovate-config-validator --strict default.json5
