name: Renovate
on:
  push:
    branches:
      - main
jobs:
  validate:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Validate
        run: npx --yes --package renovate -- renovate-config-validator --strict default.json5
