name: Renovate Config Validator
on:
  push:
    branches:
      - main
jobs:
  renovate-config-validator:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - name: Setup Node
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: 22
      - name: Install renovate
        run: npm install renovate@38
      - name: Validate renovate.json
        run: npx renovate-config-validator --strict default.json5
