name: Renovate
on:
  push:
  schedule:
    - cron: '0/5 * * * *'
jobs:
  renovate:
    runs-on: ubuntu-24.04
    steps:
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@v1.0.0
        with:
          private-key: ${{ secrets.PRIVATE_KEY }}
          app-id: ${{ secrets.APP_ID}}
          # owner: ${{ github.repository_owner }}
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.2.2
        with:
          configurationFile: renovate-config.json
          token: '${{ steps.get_token.outputs.token }}'
  
