name: Renovate
on:
  push:
    branches:
      - main
jobs:
  validate:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: Validate
        run: npx --yes --package renovate -- renovate-config-validator --strict default.json5
