name: Renovate Config Validator
on:
  push:
    branches:
      - main
jobs:
  renovate-config-validator:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Setup Node
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: 24
      - name: Install renovate
        run: npm install renovate
      - name: Validate renovate.json
        run: npx renovate-config-validator --strict default.json5
