name: Renovate
on:
  push:
    branches:
      - main
jobs:
  validate:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - name: Validate
        run: npx --yes --package renovate -- renovate-config-validator --strict default.json5
