name: Renovate Config Validator
on:
  push:
    branches:
      - main
jobs:
  renovate-config-validator:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Node
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: 22
      - name: Install renovate
        run: npm install renovate@38
      - name: Validate renovate.json
        run: npx renovate-config-validator --strict default.json5
