name: Renovate Config Validator
on:
  push:
    branches:
      - main
jobs:
  renovate-config-validator:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Setup Node
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: 22
      - name: Install renovate
        run: npm install renovate@37.430.0
      - name: Validate renovate.json
        run: npx renovate-config-validator --strict default.json5
