name: Renovate Config Validator
on:
  push:
    branches:
      - main
jobs:
  renovate-config-validator:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 24
      - name: Install renovate
        run: npm install renovate
      - name: Validate renovate.json
        run: npx renovate-config-validator --strict default.json5
