name: Renovate
on:
  push:
    branches:
      - main
jobs:
  validate:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - name: Validate
        run: npx --yes --package renovate -- renovate-config-validator --strict default.json5
