name: Renovate
on:
  push
jobs:
  validate:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Validate
        run: npx --yes --package renovate -- \
          renovate-config-validator --strict default.json
